// =============================================================
// src/main.ts — NestJS Application Entry Point (Spec-Driven)
//
// SPEC-DRIVEN APPROACH:
//   In code-first development, Swagger docs are generated FROM the code
//   (decorators like @ApiProperty, @ApiOperation, etc.).
//
//   In spec-driven development, it works the other way:
//   - We write spec/openapi.yaml FIRST (the contract)
//   - We serve that YAML file directly as the API documentation
//   - The code IMPLEMENTS what the spec describes
//   - The spec is never auto-generated — it's hand-crafted and always accurate
//
// HOW THE SPEC IS SERVED:
//   1. We read spec/openapi.yaml at startup
//   2. We parse the YAML into a JavaScript object
//   3. swagger-ui-express renders it as an interactive UI at /docs
//   4. swagger-ui-express also serves the raw JSON at /docs/spec.json
//      (useful for code generation tools)
// =============================================================

import 'reflect-metadata';
import { NestFactory } from '@nestjs/core';
import { ValidationPipe } from '@nestjs/common';
import { NestExpressApplication } from '@nestjs/platform-express';
import * as swaggerUi from 'swagger-ui-express';
import * as yaml from 'js-yaml';
import { readFileSync } from 'fs';
import { resolve } from 'path';
import * as dotenv from 'dotenv';
import { AppModule } from './app.module';

dotenv.config();

async function bootstrap() {
  const app = await NestFactory.create<NestExpressApplication>(AppModule);

  // --- Load the OpenAPI spec from YAML ---
  // resolve() gives us an absolute path regardless of where we run the server.
  // readFileSync reads the file synchronously (fine here — startup only).
  // yaml.load() parses YAML text into a plain JavaScript object.
  const specPath = resolve(__dirname, '..', 'spec', 'openapi.yaml');
  let apiSpec: object;
  try {
    const specText = readFileSync(specPath, 'utf8');
    apiSpec = yaml.load(specText) as object;
    console.log('✓ OpenAPI spec loaded from spec/openapi.yaml');
  } catch (err) {
    console.error(`✗ Failed to load spec/openapi.yaml: ${err.message}`);
    process.exit(1); // Can't run without a valid spec
  }

  // --- Serve Swagger UI from the spec YAML ---
  // This is the key difference from code-first:
  // We pass the raw spec object — not something generated by @nestjs/swagger.
  //
  // swagger-ui-express mounts two things:
  //   GET /docs       → interactive HTML UI
  //   GET /docs/spec  → raw JSON (for code generators, Postman, etc.)
  app.use('/docs', swaggerUi.serve, swaggerUi.setup(apiSpec, {
    customSiteTitle: 'RAG System API',
    swaggerOptions: {
      url: '/docs/spec',           // Tell Swagger UI where to fetch the spec
      persistAuthorization: true,
    },
  }));

  // Serve the raw spec as JSON (OpenAPI spec can be YAML or JSON)
  app.use('/docs/spec', (_req, res) => res.json(apiSpec));

  // --- Global Validation Pipe ---
  // Validates request bodies against the DTOs (which mirror spec schemas).
  app.useGlobalPipes(new ValidationPipe({
    whitelist: true,      // Strip unknown fields
    transform: true,      // Auto-convert types
    forbidNonWhitelisted: false,
  }));

  // --- CORS ---
  app.enableCors();

  const port = process.env.PORT || 3000;
  await app.listen(port);

  console.log(`\n✅ RAG System running (spec-driven)`);
  console.log(`   API:       http://localhost:${port}`);
  console.log(`   Docs:      http://localhost:${port}/docs`);
  console.log(`   Spec JSON: http://localhost:${port}/docs/spec\n`);
}

bootstrap();
