// =============================================================
// src/rag/rag.controller.ts — HTTP Route Controller
//
// WHAT IS A CONTROLLER?
//   A controller handles incoming HTTP requests and sends responses.
//   Each method maps to one HTTP endpoint (route).
//
// NESTJS ROUTE DECORATORS:
//   @Get('/path')    → HTTP GET    /path
//   @Post('/path')   → HTTP POST   /path
//   @Delete('/path') → HTTP DELETE /path
//
// @ApiTags, @ApiOperation, @ApiResponse:
//   These decorators add metadata for the Swagger docs at /docs.
//   They don't affect how the endpoint works — only how it's documented.
//
// @Body() extracts the JSON request body (automatically validated via DTO).
// =============================================================

import {
  Controller,
  Get,
  Post,
  Delete,
  Body,
  HttpCode,
  HttpStatus,
} from '@nestjs/common';
import {
  ApiTags,
  ApiOperation,
  ApiResponse,
  ApiOkResponse,
  ApiCreatedResponse,
} from '@nestjs/swagger';
import { RagService } from './rag.service';
import { AskQuestionDto, AskResponseDto } from './dto/ask-question.dto';
import { IndexDataDto } from './dto/index-data.dto';
import { SheetsService } from '../google/sheets.service';
import { VectorStoreService } from '../vector-store/vector-store.service';
import { EmbeddingsService } from '../embeddings/embeddings.service';

// @ApiTags groups endpoints in the Swagger UI under a heading
@ApiTags('RAG')
@Controller() // This controller handles routes at the root level
export class RagController {
  // DEPENDENCY INJECTION:
  // NestJS reads the constructor parameters and injects the services.
  constructor(
    private readonly ragService: RagService,
    private readonly sheetsService: SheetsService,
    private readonly vectorStoreService: VectorStoreService,
    private readonly embeddingsService: EmbeddingsService,
  ) {}

  // -----------------------------------------------------------
  // GET /health
  // -----------------------------------------------------------
  @ApiTags('System')
  @ApiOperation({ summary: 'Check server health and index status' })
  @ApiOkResponse({
    description: 'Server is running',
    schema: {
      example: { status: 'ok', indexSize: 120, model: 'Xenova/all-MiniLM-L6-v2' },
    },
  })
  @Get('health')
  health() {
    return {
      status: 'ok',
      indexSize: this.vectorStoreService.size,
      model: this.embeddingsService.getModelName(),
    };
  }

  // -----------------------------------------------------------
  // GET /
  // -----------------------------------------------------------
  @ApiOperation({ summary: 'API root — quick info' })
  @Get()
  root() {
    return {
      message: 'RAG System API is running!',
      docs: 'Visit /docs for interactive API documentation',
      health: 'Visit /health for server status',
    };
  }

  // -----------------------------------------------------------
  // POST /ask
  // -----------------------------------------------------------
  @ApiTags('RAG')
  @ApiOperation({ summary: 'Ask a question about your data' })
  @ApiCreatedResponse({ type: AskResponseDto, description: 'Answer generated by Claude' })
  @ApiResponse({ status: 503, description: 'Index not built yet — call POST /data/index first' })
  @Post('ask')
  @HttpCode(HttpStatus.OK) // Return 200, not default 201 for POST
  async ask(@Body() dto: AskQuestionDto): Promise<AskResponseDto> {
    return this.ragService.ask(dto);
  }

  // -----------------------------------------------------------
  // DELETE /history
  // -----------------------------------------------------------
  @ApiTags('RAG')
  @ApiOperation({ summary: 'Clear conversation history to start a fresh session' })
  @ApiOkResponse({ schema: { example: { message: 'Conversation history cleared.' } } })
  @Delete('history')
  clearHistory() {
    this.ragService.clearHistory();
    return { message: 'Conversation history cleared.' };
  }

  // -----------------------------------------------------------
  // POST /data/index
  // -----------------------------------------------------------
  @ApiTags('Data')
  @ApiOperation({ summary: 'Build or rebuild the vector index from Google Sheets and/or Drive' })
  @ApiCreatedResponse({
    schema: { example: { message: 'Indexed 120 chunks successfully.', chunkCount: 120 } },
  })
  @Post('data/index')
  @HttpCode(HttpStatus.OK)
  async index(@Body() dto: IndexDataDto) {
    return this.ragService.indexData(dto);
  }

  // -----------------------------------------------------------
  // GET /data/sheets
  // -----------------------------------------------------------
  @ApiTags('Data')
  @ApiOperation({ summary: 'List all worksheet tab names in the Google Spreadsheet' })
  @ApiOkResponse({ schema: { example: { sheetNames: ['Sheet1', 'Products', 'FAQ'] } } })
  @Get('data/sheets')
  async listSheets() {
    const sheetNames = await this.sheetsService.getSheetNames();
    return { sheetNames };
  }

  // -----------------------------------------------------------
  // POST /data/backup
  // -----------------------------------------------------------
  @ApiTags('Data')
  @ApiOperation({ summary: 'Backup the current index to Google Drive' })
  @ApiOkResponse({ schema: { example: { message: 'Backup complete.', driveFileId: 'abc123' } } })
  @Post('data/backup')
  @HttpCode(HttpStatus.OK)
  async backup() {
    const driveFileId = await this.ragService.backupToDrive();
    return { message: 'Backup complete.', driveFileId };
  }

  // -----------------------------------------------------------
  // POST /data/restore
  // -----------------------------------------------------------
  @ApiTags('Data')
  @ApiOperation({ summary: 'Restore the index from a Google Drive backup' })
  @ApiOkResponse({ schema: { example: { message: 'Restore complete.', chunkCount: 120 } } })
  @Post('data/restore')
  @HttpCode(HttpStatus.OK)
  async restore() {
    const ok = await this.ragService.restoreFromDrive();
    return ok
      ? { message: 'Restore complete.', chunkCount: this.vectorStoreService.size }
      : { message: 'No backup found on Drive.' };
  }
}
